version: '3.8'

services:
  mysql-db:
    image: mysql:8.4
    container_name: telemetry-mysql-container
    restart: always
    environment:
      # CRITICAL: MySQL requires a root password configuration to boot up successfully
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_DEV_USER}
      MYSQL_PASSWORD: ${DB_DEV_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_84_data:/var/lib/mysql

volumes:
  mysql_84_data:
